#Config Spring Security Oauth2 as Authorization Server
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

#Config Facebook as Authorization Server
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

#Config Github as Authorization Server
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user


#Spring Configuration
spring:

  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    url: jdbc:mysql://localhost:3306/belajar_oauth
    username: belajar
    password: belajar


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: clorus.id@gmail.com
    password: clorus2017
    properties:
      mail:
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true
          connectiontimeout: 5000
          timemout: 5000
          writetimeout: 5000

#Server Configuration
server:
  port: 8080
  session:
    cookie:
      name: AUTHSERVER


upload:
  data:
    dir: /home/ciazhar
